theme = "oxocarbon"

[editor]
line-number = "relative"
cursorline = true
mouse = false
completion-trigger-len = 1
color-modes = true

[editor.lsp]
display-signature-help-docs = false


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
space = "all"
nbsp = "all"
tab = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "→" # Tabs will look like "→···" (depending on tab width)


[editor.indent-guides]
render = true
character = "→" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 0

[keys.normal]
";"="command_mode"
n="move_char_left"
e="move_line_down"
i="move_line_up"
o="move_char_right"

u="insert_mode"
U="insert_at_line_start"

l="undo"
L="redo"

y="open_below"
Y="open_above"

r="move_next_word_end"
R="move_next_long_word_end"

j="search_next"
J="search_prev"

[keys.normal.g]
n="goto_line_start"
o="goto_line_end"

[keys.normal.space.w]
n="jump_view_left"
e="jump_view_down"
i="jump_view_up"
o="jump_view_right"

[keys.normal.C-w]
n="jump_view_left"
e="jump_view_down"
E="join_selections"
"A-E"="join_selections_space"

i="jump_view_up"
I="keep_selections"
"A-I"="remove_selections"

o="jump_view_right"

[keys.insert]
"e" = {i = "normal_mode"} # Maps Alt-X to eieieieiei`enter normal mode


[keys.select]
n="move_char_left"
e="move_line_down"
i="move_line_up"
o="move_char_right"

h="insert_mode"
H="insert_at_line_start"

l="open_below"
L="open_above"

k="move_next_word_end"
K="move_next_long_word_end"

j="search_next"
J="search_prev"

[keys.normal.z]
e="scroll_down"
i="scroll_up"

[keys.normal.Z]
e="scroll_down"
i="scroll_up"


# [keys.normal]
# "space-space" = "open_filepicker"