[[language]]
name = "go"
formatter = { command = "goimports" }
language-servers = [ "gopls", "ltex-ls"]

[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md|markdown"
file-types = ["md", "markdown", "PULLREQ_EDITMSG"]
roots = [".marksman.toml"]
language-servers = [ "marksman", "ltex-ls"]
indent = { tab-width = 2, unit = "  " }


# [[language]]
# name = "fennel"

